### PR TITLE
Changed websockify to websockify.js

### PR DESCRIPTION
**Pull request by krasnikau-andrei**
Websockify requires python for work and also have very poor support on Windows. I changed it to websockify.js so we can install all dependencies by `npm install`

### CODE REVIEW

**Comment by krasnikau-andrei** [comment]
Warning: its not tested on linux

**Comment by alexchandel** [comment]
Looks good.

I looked into websockify.js when I wrote this, but it seemed like it missed some features.  Does it handle when the client dies?

**Comment by krasnikau-andrei** [comment]
Yes

**Comment by alexchandel** [comment]
@krasnikov-andrew Websockify.js does not seem to work.  It errors with `protocols.indexOf('binary')` is not defined.  Did you test this?

**Pull request merged**
